apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    protocol: TCP
    nodePort: 30080
    name: port0
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
